development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: polariscope_two_dev
  pool: 5
  username: <%= ENV['PSAAPPMYSQLUSERNAME'] %>
  password: <%= ENV['PSAAPPMYSQLPASSWORD'] %>
  socket: <%= ENV['PSAAPPMYSQLSOCKETLOCATION'] %>
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: polariscope_two_test
  pool: 5
  username: <%= ENV['PSAAPPMYSQLUSERNAME'] %>
  password: <%= ENV['PSAAPPMYSQLPASSWORD'] %>
  socket: <%= ENV['PSAAPPMYSQLSOCKETLOCATION'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: polariscope_two
  pool: 5
  username: <%= ENV['PSAAPPMYSQLUSERNAME'] %>
  password: <%= ENV['PSAAPPMYSQLPASSWORD'] %>
  socket: <%= ENV['PSAAPPMYSQLSOCKETLOCATION'] %>
