development:
  url: http://localhost:4000
  email: 124903@rakuten.com
  token: KGCuaB-jVoQqwG9XCsL7
test:
  url: http://localhost:5000
  email: 124903@rakuten.com
  token: KGCuaB-jVoQqwG9XCsL7
production:
  url: <%= ENV["WEB_ACTION_API_URL"] %>
  email: <%= ENV["WEB_ACTION_API_EMAIL"] %>
  token: <%= ENV["WEB_ACTION_API_TOKEN"] %>
