require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TestActionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # TestAction. As you add validations to TestAction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TestActionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all test_actions as @test_actions" do
      test_action = TestAction.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:test_actions)).to eq([test_action])
    end
  end

  describe "GET #show" do
    it "assigns the requested test_action as @test_action" do
      test_action = TestAction.create! valid_attributes
      get :show, {:id => test_action.to_param}, valid_session
      expect(assigns(:test_action)).to eq(test_action)
    end
  end

  describe "GET #new" do
    it "assigns a new test_action as @test_action" do
      get :new, {}, valid_session
      expect(assigns(:test_action)).to be_a_new(TestAction)
    end
  end

  describe "GET #edit" do
    it "assigns the requested test_action as @test_action" do
      test_action = TestAction.create! valid_attributes
      get :edit, {:id => test_action.to_param}, valid_session
      expect(assigns(:test_action)).to eq(test_action)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new TestAction" do
        expect {
          post :create, {:test_action => valid_attributes}, valid_session
        }.to change(TestAction, :count).by(1)
      end

      it "assigns a newly created test_action as @test_action" do
        post :create, {:test_action => valid_attributes}, valid_session
        expect(assigns(:test_action)).to be_a(TestAction)
        expect(assigns(:test_action)).to be_persisted
      end

      it "redirects to the created test_action" do
        post :create, {:test_action => valid_attributes}, valid_session
        expect(response).to redirect_to(TestAction.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved test_action as @test_action" do
        post :create, {:test_action => invalid_attributes}, valid_session
        expect(assigns(:test_action)).to be_a_new(TestAction)
      end

      it "re-renders the 'new' template" do
        post :create, {:test_action => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested test_action" do
        test_action = TestAction.create! valid_attributes
        put :update, {:id => test_action.to_param, :test_action => new_attributes}, valid_session
        test_action.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested test_action as @test_action" do
        test_action = TestAction.create! valid_attributes
        put :update, {:id => test_action.to_param, :test_action => valid_attributes}, valid_session
        expect(assigns(:test_action)).to eq(test_action)
      end

      it "redirects to the test_action" do
        test_action = TestAction.create! valid_attributes
        put :update, {:id => test_action.to_param, :test_action => valid_attributes}, valid_session
        expect(response).to redirect_to(test_action)
      end
    end

    context "with invalid params" do
      it "assigns the test_action as @test_action" do
        test_action = TestAction.create! valid_attributes
        put :update, {:id => test_action.to_param, :test_action => invalid_attributes}, valid_session
        expect(assigns(:test_action)).to eq(test_action)
      end

      it "re-renders the 'edit' template" do
        test_action = TestAction.create! valid_attributes
        put :update, {:id => test_action.to_param, :test_action => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested test_action" do
      test_action = TestAction.create! valid_attributes
      expect {
        delete :destroy, {:id => test_action.to_param}, valid_session
      }.to change(TestAction, :count).by(-1)
    end

    it "redirects to the test_actions list" do
      test_action = TestAction.create! valid_attributes
      delete :destroy, {:id => test_action.to_param}, valid_session
      expect(response).to redirect_to(test_actions_url)
    end
  end

end
